import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { poppins, lato, oswald, sacramento } from "@/assets/fonts/Fonts";
import ThemeProvider from "@/context/ThemeProvider";

export const metadata: Metadata = {
  title: "Lorienleaf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${poppins.variable}
      
        ${lato.variable}
        ${oswald.variable}
        ${sacramento.variable}
      `}
    >
      <head></head>
      <body className="bg-bg-primary">
        <ThemeProvider>
          <Navbar />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
